/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package background;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author TRAN VAN TRI
 */
public class coffe extends javax.swing.JDialog {

    /**
     * Creates new form coffe
     */
    private String namee;
    private String costt;
    private final user users;

    public coffe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        users = (user) parent;
        setLocationRelativeTo(null);
        showdatae();
        fomat();
        name.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                String choose = (String) name.getSelectedItem();
                String type = (String) size.getSelectedItem();
                try {
                    Scanner sc = new Scanner(new FileReader("cfe.txt"));
                    while (sc.hasNextLine()) {
                        String temp = sc.next();
                        if (temp.equals(choose)) {
                            if (type.equalsIgnoreCase("normal")) {
                                cost.setText(sc.next());
                            } else if (type.equalsIgnoreCase("big")) {
                                int tem = Integer.parseInt(sc.next()) + 10000;
                                String pr = Integer.toString(tem);
                                cost.setText(pr);

                            } else {
                                int tem = Integer.parseInt(sc.next()) - 5000;
                                String pr = Integer.toString(tem);
                                cost.setText(pr);
                            }

                        }
//            
                    }
                } catch (Exception e) {
                }
            }
        });
        size.addActionListener(name);
        try {
            Scanner sc = new Scanner(new FileReader("cfe.txt"));
            while (sc.hasNextLine()) {
                namee = sc.next();
                costt = sc.next();
                name.addItem(namee);
            }
        } catch (FileNotFoundException e) {

        } catch (Exception e) {
        }

    }

    private void fomat() {

        add.setText("Add Item");
        add.setBackground(Color.pink);
        add.setFont(new Font(" ", Font.BOLD, 15));
        add.setForeground(Color.yellow);
        close.setText(" Close ");
        close.setBackground(Color.black);
        close.setFont(new Font(" ", Font.BOLD, 15));
        close.setForeground(Color.yellow);
    }

    private void showdatae() {
        List<String> data = source_price.getsprice();
        for (String string : data) {
            size.addItem(string);
        }
    }

    private static boolean isNumeric(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        size = new javax.swing.JComboBox<>();
        num = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        close = new javax.swing.JButton();
        name = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        num.setText("jTextField1");

        cost.setText("jTextField2");

        add.setText("jButton1");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        close.setText("jButton2");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(close)
                            .addComponent(add)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(309, Short.MAX_VALUE)
                        .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(add)
                .addGap(18, 18, 18)
                .addComponent(close)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String Name = "";
        double costs = 0;
        int nums = 0;
        boolean done = true;

        Name = (String) name.getSelectedItem();
        String type = (String) size.getSelectedItem();

        try {
            nums = Integer.parseInt(num.getText());
            costs = Double.parseDouble(cost.getText()) * Integer.parseInt(num.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "you must enter number");
            done = false;
        }
        if (done) {
            sourceOFmilktea sOf = new sourceOFmilktea(Name, type, costs, nums);
            users.addMilkTea(sOf);
            JOptionPane.showMessageDialog(null, " complete");

        }
    }//GEN-LAST:event_addActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coffe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coffe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coffe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coffe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                coffe dialog = new coffe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton close;
    private javax.swing.JTextField cost;
    private javax.swing.JComboBox<String> name;
    private javax.swing.JTextField num;
    private javax.swing.JComboBox<String> size;
    // End of variables declaration//GEN-END:variables
}
