/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package background;

import java.awt.Color;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.List;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author TRAN VAN TRI
 */
public class milktea extends javax.swing.JDialog {

    /**
     * Creates new form milktea
     */
    private String namee;
    private String costt;
    private final user users;
    private String[] nameItem;
    private String[] money;

    public milktea(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        users = (user) parent;
        this.setTitle("input some thing ");
        showdata1();

        try {
            Scanner sc = new Scanner(new FileReader("milktea.txt"));
            while (sc.hasNextLine()) {
                namee = sc.next();
                costt = sc.next();
                name.addItem(namee);

            }
        } catch (FileNotFoundException e) {

        } catch (Exception e) {
        }
        format();

    }

    private static boolean isNumeric(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void format() {
        getContentPane().setBackground(Color.ORANGE);
        getContentPane().setForeground(Color.red);
        jLabel1.setText("Lordland's Milktea");
        jLabel1.setBackground(Color.black);
        jLabel1.setFont(new Font(" ", Font.BOLD, 25));
        jLabel1.setForeground(Color.red);
        num.setText("");
        num.setForeground(Color.red);
        updatecost.setText(" Display Cost ");
        cost.setText(" Price Item ");
        cost.setForeground(Color.pink);
        cost.setFont(new Font(" ", Font.CENTER_BASELINE, 15));
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/background/Icon/price.png")));
        jLabel2.setText("");
        addnew.setText(" Add Item ");
        addnew.setForeground(Color.green);
        addnew.setIcon(new ImageIcon(getClass().getResource("/background/Icon/zohang.png")));
        addnew.setBackground(Color.red);
        addnew.setFont(new Font("", Font.BOLD, 15));
        close.setForeground(Color.red);
        close.setText(" Close ");
        close.setFont(new Font("", Font.BOLD, 15));
        size.setForeground(Color.red);
        size.setFont(new Font("", Font.BOLD, 15));
        name.setForeground(Color.red);
        name.setFont(new Font(" ", Font.BOLD, 15));
        updatecost.setForeground(Color.red);
        updatecost.setBackground(Color.blue);

    }

    private void showdata1() {
        List<String> data = size_box.getdata();
        for (String string : data) {
            size.addItem(string);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addnew = new javax.swing.JButton();
        cost = new javax.swing.JTextField();
        num = new javax.swing.JTextField();
        size = new javax.swing.JComboBox<>();
        close = new javax.swing.JButton();
        name = new javax.swing.JComboBox<>();
        updatecost = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addnew.setText("jButton1");
        addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewActionPerformed(evt);
            }
        });

        cost.setText("cost");
        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });

        num.setText("jTextField1");

        size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeActionPerformed(evt);
            }
        });

        close.setText("jButton2");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        updatecost.setText("jButton1");
        updatecost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecostActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(cost)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close)
                    .addComponent(addnew)
                    .addComponent(updatecost))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addnew)
                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatecost)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewActionPerformed
        // TODO add your handling code here:
        String Name = "";
        double costs = 0;
        int nums = 0;
        boolean done = true;

        Name = (String) name.getSelectedItem();
        //   int index = size.getSelectedIndex();
        /* if(index>0){
           String selecdata = size_box.getdata().get(index);
        }*/
        String type = (String) size.getSelectedItem();

        try {
            nums = Integer.parseInt(num.getText());
            costs = Double.parseDouble(cost.getText()) * Integer.parseInt(num.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "you must enter number");
            done = false;
        }
        if (done) {
            sourceOFmilktea sOf = new sourceOFmilktea(Name, type, costs, nums);
            users.addMilkTea(sOf);
            JOptionPane.showMessageDialog(null, " complete");

        }
    }//GEN-LAST:event_addnewActionPerformed

    private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed

    }//GEN-LAST:event_costActionPerformed

    private void sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_sizeActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed

        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void updatecostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecostActionPerformed
        // TODO add your handling code here:
        String choose = (String) name.getSelectedItem();
        int count = name.getItemCount();
        String[] nameItem = new String[count];
        String[] money = new String[count];
        try {
            Scanner sc = new Scanner(new FileReader("milktea.txt"));
            while (sc.hasNextLine()) {
                String temp = sc.next();
                if (temp.equals(choose)) {
                    cost.setText(sc.next());
                }
//            
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_updatecostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(milktea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(milktea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(milktea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(milktea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                milktea dialog = new milktea(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnew;
    private javax.swing.JButton close;
    private javax.swing.JTextField cost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> name;
    private javax.swing.JTextField num;
    private javax.swing.JComboBox<String> size;
    private javax.swing.JButton updatecost;
    // End of variables declaration//GEN-END:variables

}
